# This is the Dockerfile that we will use to build the image
# and run the container
# Start with a base image
FROM node:14-alpine as build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json to the working directory and install dependencies
COPY package*.json ./
RUN npm install

# Copy the source code to the working directory
COPY . .

# Reduce the image size using multi-stage builds
# Use distroless base image
FROM gcr.io/distroless/nodejs:14

# Set the working directory
WORKDIR /app

# Copy built application from the build stage
COPY --from=build /app /app

# Expose the port on which the application will run
EXPOSE 3000

# Define the command to run the application
CMD ["app.js"]
